FROM almalinux:9
# we can override this in commad line
#CMD ["ping", "yahoo.com"]     

# we can't override this in commad line
#ENTRYPOINT [ "ping", "yahoo.com" ]     

#  by default pings yahoo, but we can override this
ENTRYPOINT [ "ping" ]
CMD ["yahoo.com"]                  