ARG version
FROM almalinux:${version:-9}
ARG course="docker" \
    trainer="vamsi" \
    duration="10hrs"
RUN echo "Course is: ${course}, Duration is: ${duration}, Trainer is: ${trainer}, version is: ${version}"
